### ISSUE TITLE
Bed presence not seeming to work? 

### ISSUE THREAD

**Issue by davidmul87** [lukas-clarke/eight_sleep#10]
Hi, 

i have the integration installed and connected and the Bed state and sleep state sensors seem to be working well but the Bed presence sensor doesn't seem to work correctly? It is just constantly showing 'clear' even when someone is in the bed and detected in various sleep states?

Regards,
David

**Comment by lukas-clarke** [comment]
Hey David, unfortunately this a restriction imposed by 8 sleep. The app API doesn't expose bed state. The bed state works by guessing patterns based on the bed temperature changes, but isn't very reliable.
The only real solution is for 8 sleep to expose the bed state in their API, which they would be able to do since the cover sends that info to their servers.
